### PR TITLE
Application icon

### PR DESCRIPTION
**Pull request by daudix-UFO**
Make an icon for this project, Idea of this icon is "Tweaking Adwaita from inside (Gear), with simple UI (Paint Roller)"

_Maybe I will improve it near future_
# Normal
Adwaita Manager

# Nightly
Adwaita Manager Devel

# Symbolic
Adwaita Manager Symbolic

📎 [Source Files and Alternative Versions](https://github.com/ArtyIF/AdwCustomizer/files/9144301/Adwaita.Manager.zip)

### CODE REVIEW

**Comment by ArtyIF** [comment]
I have some suggestions to improve this:

1) Make the roller's paint part have separate distinct colors instead of a gradient and have it ordered in the way Adwaita orders them, something like this (maybe no brown):
image
2) The roller shouldn't really be painted with the yellow-and-black pattern in the nightly logo
3) The symbolic icon is quite a bit different from the regular icon. I like the idea in #2 with it just being the roller

**Comment by daudix-UFO** [comment]
Will do it in a few minutes!

**Comment by daudix-UFO** [comment]
Sorry for waiting a hour instead of "A Few minutes", I don't expected that will take that long...

**Comment by daudix-UFO** [comment]
For some reason, icon looks strange compared to other icons, what can we improve to make it better (maybe removing paint roller?)
image
Снимок экрана от 2022-07-20 01-06-20

**Comment by daudix-UFO** [comment]
Another variant:

Снимок экрана от 2022-07-20 01-31-28

**Pull request closed without merging**
