### PR TITLE
Polish icons

### PR DESCRIPTION
**Pull request by daudix-UFO**
# Changes:

- Roller on app icon have been redrawn from scratch
- Added Source for app icon
- Symbolic app icon have been optimized
- adw-gtk3 warning icon have a bit improved transparency
- controls icon in /src/icons/icon-dev-kit has been replaced with custom palette icon (inspired by [Palette](https://apps.gnome.org/app/org.gnome.design.Palette/) app symbolic)
- name of palette icon has been replaced in .gresource and .blp files

### CODE REVIEW

**Comment by ArtyIF** [comment]
Can you move the palette icon out of the "icon-dev-kit" directory and rename it similar to the adw-gtk3 warning icon please? That directory was meant for icons from Icon Development Kit.

**Comment by ArtyIF** [comment]
And I don't think there's much point in the source file

**Comment by daudix-UFO** [comment]
> And I don't think there's much point in the source file

OK, I will remove it

**Comment by daudix-UFO** [comment]
> Can you move the palette icon out of the "icon-dev-kit" directory and rename it similar to the adw-gtk3 warning icon please? That directory was meant for icons from Icon Development Kit.

Will do it RN

**Comment by daudix-UFO** [comment]
Done!

**Pull request merged**
