### PR TITLE
Polish app icon (hicolor & symbolic)

### PR DESCRIPTION
**Pull request by daudix-UFO**
Re-draw of current icon, improved a lot of things, but in short, looks more sweet

# Normal

Adwaita Manager 3

# Symbolic

Adwaita Manager Symbolic

# In Use

### Light

About Light

### Dark
About Dark

### App grid

Sound Recorder - Obfuscate - Adwaita Manager

### Symbolic in top bar

Symbolic

[📎 Source & Alternative versions](https://github.com/ArtyIF/AdwCustomizer/files/9160301/Adwaita.Manager.zip)

### CODE REVIEW

**Comment by ArtyIF** [comment]
Yeah, that looks nicer, especially the metal bracket. But I would prefer the stripes on the window to have the same opacity.

**Comment by daudix-UFO** [comment]
> Yeah, that looks nicer, especially the metal bracket. But I would prefer the stripes on the window to have the same opacity.

They all use 70% opacity

**Comment by ArtyIF** [comment]
I mean the same as the original. Слишком бледными выглядят 17:56, July 21, 2022, David Lapshin ***@***.***>:

Yeah, that looks nicer, especially the metal bracket. But I would prefer the stripes on the window to have the same opacity.

They all use 70% opacity

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by daudix-UFO** [comment]
Готово, очень тупая ошибка :(
Снимок экрана от 2022-07-21 18-02-45

**Comment by ArtyIF** [comment]
I got a new version coming up soon, after I finish it I'll merge this

**Comment by daudix-UFO** [comment]
nice!

**Pull request merged**
